{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lookout.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lookout.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "lookout.selectorLabels" . | nindent 4 }}
{{- end }}
