// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package skilldoc generates the per-command reference stubs under
// skills/<skill>/references/ from the pkg/checks command metadata —
// the third generated surface after --help and the MCP schemas
// (DESIGN.md §4.4.3: one source of truth, generated outward). The
// committed files are regenerated by dev/tools/gen-skill-refs; a
// drift test in this package fails CI when a metadata change is not
// followed by a re-run.
package skilldoc

import (
	"fmt"
	"sort"
	"strings"

	"github.com/go-steer/k8s-lookout/pkg/checks"
	"github.com/go-steer/k8s-lookout/pkg/emit"
)

// Header is stamped on every generated file so a human editing one
// by hand is warned before the drift test tells them the hard way.
const Header = "<!-- Generated by dev/tools/gen-skill-refs from pkg/checks command metadata. DO NOT EDIT. -->"

// SkillCommands maps each shipped workflow skill to the commands
// whose reference stubs live under skills/<skill>/references/. A
// command may back several skills; the stubs are duplicated on
// purpose so an installed skill directory is self-contained
// (§4.4.2: references load only when a command is actually being
// run — they must be reachable from the skill that triggered).
var SkillCommands = map[string][]string{
	"k8s-triage": {"bundle", "triage delta", "triage logs", "triage spec",
		"triage events", "triage radius", "triage changes", "state edges", "net probe"},
	"cluster-health": {"health", "triage delta", "state edges", "bundle",
		"triage radius", "triage changes"},
}

// RefFileName returns the reference-stub file name for a command
// name: "triage delta" → "triage-delta.md".
func RefFileName(command string) string {
	return strings.ReplaceAll(command, " ", "-") + ".md"
}

// GenerateAll renders every reference stub for every skill in
// SkillCommands. Keys are paths relative to the repository root
// (skills/<skill>/references/<command>.md).
func GenerateAll(reg *checks.Registry) (map[string]string, error) {
	out := map[string]string{}
	skills := make([]string, 0, len(SkillCommands))
	for s := range SkillCommands {
		skills = append(skills, s)
	}
	sort.Strings(skills)
	for _, skill := range skills {
		for _, name := range SkillCommands[skill] {
			c, ok := reg.Lookup(name)
			if !ok {
				return nil, fmt.Errorf("skill %q references unregistered command %q", skill, name)
			}
			if c.Hidden {
				return nil, fmt.Errorf("skill %q references hidden command %q", skill, name)
			}
			path := "skills/" + skill + "/references/" + RefFileName(name)
			out[path] = ReferenceDoc(c)
		}
	}
	return out, nil
}

// ReferenceDoc renders one command's reference stub: the level-3
// deep doc of the progressive-disclosure ladder (§4.4.2) — full flag
// detail, the output-field glossary, and the shared envelope
// semantics, from the same declaration that generates --help and
// the MCP schema.
func ReferenceDoc(c checks.Command) string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n\n# lookout %s\n\n%s\n\n", Header, c.Name, c.Summary)
	fmt.Fprintf(&b, "MCP tool: `%s`\n\n", c.MCPName)

	b.WriteString("## Usage\n\n")
	if c.Positional != nil {
		fmt.Fprintf(&b, "    lookout %s %s [flags]\n\n", c.Name, c.Positional.Meta)
		fmt.Fprintf(&b, "`%s` — %s\n\n", c.Positional.Meta, c.Positional.Doc)
	} else {
		fmt.Fprintf(&b, "    lookout %s [flags]\n\n", c.Name)
	}

	if len(c.Flags) > 0 {
		b.WriteString("## Flags\n\n")
		writeFlagTable(&b, c.Flags)
	}
	b.WriteString("## Common flags (every lookout command)\n\n")
	writeFlagTable(&b, emit.CommonFlags())

	if len(c.Output) > 0 {
		fmt.Fprintf(&b, "## Output fields\n\nBeyond the shared envelope fields (%s):\n\n",
			"`"+strings.Join(emit.EnvelopeFields(), "`, `")+"`")
		b.WriteString("| Field | Meaning |\n| --- | --- |\n")
		for _, f := range c.Output {
			fmt.Fprintf(&b, "| `%s` | %s |\n", f.Name, cell(f.Doc))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Output contract\n\n" + checks.EnvelopeContract() + "\n")

	if len(c.Examples) > 0 {
		b.WriteString("\n## Examples\n\n```lookout\n")
		for _, e := range c.Examples {
			b.WriteString(e + "\n")
		}
		b.WriteString("```\n")
	}
	return b.String()
}

// writeFlagTable renders flag specs as a markdown table, defaults
// inline — same discipline as the --help flag table.
func writeFlagTable(b *strings.Builder, specs []emit.FlagSpec) {
	b.WriteString("| Flag | Default | Meaning |\n| --- | --- | --- |\n")
	for _, s := range specs {
		dash := "--"
		if len(s.Name) == 1 {
			dash = "-"
		}
		def := s.Default
		switch {
		case s.Type == emit.FlagBool, def == "", def == "0s", def == "0":
			def = "—"
		}
		fmt.Fprintf(b, "| `%s%s` | %s | %s |\n", dash, s.Name, cell(def), cell(s.Help))
	}
	b.WriteString("\n")
}

// cell escapes a string for use inside a markdown table cell.
func cell(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
