// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package skilldoc_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-steer/k8s-lookout/internal/skilldoc"
	"github.com/go-steer/k8s-lookout/pkg/checks"

	_ "github.com/go-steer/k8s-lookout/pkg/checks/bundle"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/cloudcheck"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/delta"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/events"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/health"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/logs"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/netprobe"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/perf"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/stab"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/state"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/triage"
)

// repoRoot is the working-tree root relative to this package.
const repoRoot = "../.."

// TestReferenceStubsAreCurrent is the §4.4.3 drift gate: the
// committed skills/*/references/*.md must be byte-identical to what
// the current pkg/checks metadata generates. On failure, run
// dev/tools/gen-skill-refs and commit the diff.
func TestReferenceStubsAreCurrent(t *testing.T) {
	files, err := skilldoc.GenerateAll(checks.Default())
	if err != nil {
		t.Fatal(err)
	}
	for rel, want := range files {
		got, err := os.ReadFile(filepath.Join(repoRoot, filepath.FromSlash(rel)))
		if err != nil {
			t.Errorf("%s: %v (run dev/tools/gen-skill-refs)", rel, err)
			continue
		}
		if string(got) != want {
			t.Errorf("%s is stale — run dev/tools/gen-skill-refs and commit the result", rel)
		}
	}

	// No stray hand-written files may hide in the generated dirs.
	for skill := range skilldoc.SkillCommands {
		dir := filepath.Join(repoRoot, "skills", skill, "references")
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatalf("%s: %v (run dev/tools/gen-skill-refs)", dir, err)
		}
		for _, e := range entries {
			rel := "skills/" + skill + "/references/" + e.Name()
			if _, ok := files[rel]; !ok {
				t.Errorf("%s: not generated by skilldoc — references/ is generated-only, move it elsewhere", rel)
			}
		}
	}
}

// TestGeneratedStubsCarryHeaderAndContract spot-checks the rendered
// shape: every stub opens with the DO NOT EDIT header and carries
// the shared §4.2 output-contract paragraph verbatim.
func TestGeneratedStubsCarryHeaderAndContract(t *testing.T) {
	files, err := skilldoc.GenerateAll(checks.Default())
	if err != nil {
		t.Fatal(err)
	}
	if len(files) == 0 {
		t.Fatal("no reference stubs generated")
	}
	for rel, content := range files {
		if !strings.HasPrefix(content, skilldoc.Header) {
			t.Errorf("%s: missing generated-file header", rel)
		}
		if !strings.Contains(content, checks.EnvelopeContract()) {
			t.Errorf("%s: missing the shared output-contract paragraph", rel)
		}
	}
}
