#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. "$(dirname "$0")/../../lib.sh"
require_examples_context

echo "▸ verify endpoints-empty"
# Same recurrence hedge as pdb-gridlock: a re-run inside the recovery
# window arrives as kind=resolved.reverted on the Service.
await_inject endpoints-empty 300 'objectstate.endpoints_empty|resolved.reverted' 'web'
await_finding 120 'selector_empty|NoMatchingPods' \
  -- state edges --workload="Deployment/$DEMO_NS/web"
