#!/usr/bin/env bash
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. "$(dirname "$0")/../../lib.sh"
require_examples_context

echo "▸ verify oom"
await_inject oom 360 'leaker-' 'BackOff|OOM|restart_burst'
await_finding 300 'leaker-.*(BackOff|OOM|ExcessiveRestarts)|(BackOff|OOM).*leaker-' \
  -- triage events --namespace="$DEMO_NS"
