// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package emit

import (
	"bytes"
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"time"
)

// Exit codes per the §4.2 contract. The multicall dispatcher and
// every check runner return these; nothing else.
const (
	ExitData    = 0 // stdout carries payload + summary
	ExitRuntime = 1 // diagnostics on stderr; stdout has no summary
	ExitUsage   = 2 // bad flags/arguments
)

// Invocation is everything a check receives: the parsed common-flag
// Scope, its own typed flags, the positional arguments (only for
// commands that declare RunConfig.MaxArgs > 0), and the output
// Writer. Checks emit findings as they discover them (streaming —
// payloads can be large) and return only the scanned count; the
// runner owns the summary line and the exit code.
type Invocation struct {
	Scope Scope
	Flags FlagValues
	Args  []string
	Out   *Writer
}

// CheckFunc is one read-path check. scanned is the number of objects
// examined, reported in the summary line so an agent can tell
// "cluster healthy" (scanned=412 findings=0) from "scoped to
// nothing" (scanned=0 findings=0). A returned error aborts the
// invocation: diagnostics to stderr, exit 1, and no summary line —
// consumers must treat a stdout stream without a terminating summary
// as void.
type CheckFunc func(ctx context.Context, inv Invocation) (scanned int, err error)

// RunConfig configures one Run. Zero values give production
// behavior; tests inject writers and the clock.
type RunConfig struct {
	// Name is the full invocation name for usage lines and
	// diagnostics, e.g. "lookout triage logs".
	Name string
	// Flags declares the command-specific flags; the §4.2 common
	// flags are always registered in addition.
	Flags []FlagSpec
	// Check is the implementation to invoke.
	Check CheckFunc
	// Help is the full --help text (generated by pkg/checks from
	// command metadata). If empty, a minimal flag listing is
	// printed instead.
	Help string
	// MaxArgs is how many positional arguments the command accepts
	// (0, the default, rejects any positional as a usage error —
	// the historical behavior). Positionals may be interspersed
	// with flags, kubectl-style, and reach the check via
	// Invocation.Args; validating their content is the check's
	// job (return a UsageErrorf error for exit 2).
	MaxArgs int
	// Stdout and Stderr default to the process streams.
	Stdout io.Writer
	Stderr io.Writer
	// Now defaults to time.Now. It is called exactly twice (start
	// and finish), so a fake clock makes the summary's elapsed
	// value deterministic for golden tests.
	Now func() time.Time
}

// Run executes one check invocation under the §4.2 contract: parse
// common + declared flags, enforce --timeout via
// context.WithTimeout, stream findings through the sanitizing
// Writer, and terminate stdout with the mandatory summary line. The
// return value is the process exit code.
func Run(ctx context.Context, cfg RunConfig, args []string) int {
	stdout, stderr := cfg.Stdout, cfg.Stderr
	if stdout == nil {
		stdout = os.Stdout
	}
	if stderr == nil {
		stderr = os.Stderr
	}
	now := cfg.Now
	if now == nil {
		now = time.Now
	}

	// Flag parsing: errors and help are rendered by us, not the
	// flag package, so stdout/stderr routing follows the contract.
	fs := flag.NewFlagSet(cfg.Name, flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	fs.Usage = func() {}
	if err := registerSpecs(fs, CommonFlags()); err != nil {
		fmt.Fprintf(stderr, "%s: %v\n", cfg.Name, err)
		return ExitRuntime // broken command definition, not user error
	}
	if err := registerSpecs(fs, cfg.Flags); err != nil {
		fmt.Fprintf(stderr, "%s: %v\n", cfg.Name, err)
		return ExitRuntime
	}
	// Parse in a loop so positionals may be interspersed with
	// flags (kubectl-style: `triage spec Pod/x --namespace=prod`):
	// the flag package stops at the first non-flag token, so each
	// pass peels one positional off and re-parses the remainder.
	var positionals []string
	rest := args
	for {
		if err := fs.Parse(rest); err != nil {
			if errors.Is(err, flag.ErrHelp) {
				fmt.Fprint(stdout, cfg.helpText(fs))
				return ExitData
			}
			return usageError(stderr, cfg.Name, err)
		}
		if fs.NArg() == 0 {
			break
		}
		positionals = append(positionals, fs.Arg(0))
		rest = fs.Args()[1:]
	}
	if len(positionals) > cfg.MaxArgs {
		return usageError(stderr, cfg.Name, fmt.Errorf("unexpected argument %q", positionals[cfg.MaxArgs]))
	}

	values := FlagValues{fs: fs}
	scope, err := scopeFromValues(values)
	if err != nil {
		return usageError(stderr, cfg.Name, err)
	}
	format, err := ParseFormat(values.String("format"))
	if err != nil {
		return usageError(stderr, cfg.Name, err)
	}
	timeout := values.Duration("timeout")
	if timeout <= 0 {
		return usageError(stderr, cfg.Name, fmt.Errorf("--timeout must be positive, got %s", timeout))
	}

	writer, err := NewWriter(stdout, format)
	if err != nil {
		fmt.Fprintf(stderr, "%s: %v\n", cfg.Name, err)
		return ExitRuntime
	}

	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	start := now()
	scanned, err := cfg.Check(ctx, Invocation{Scope: scope, Flags: values, Args: positionals, Out: writer})
	if err != nil {
		if IsUsageError(err) {
			return usageError(stderr, cfg.Name, err)
		}
		if errors.Is(err, context.DeadlineExceeded) {
			fmt.Fprintf(stderr, "%s: timed out after %s\n", cfg.Name, timeout)
		} else {
			fmt.Fprintf(stderr, "%s: %v\n", cfg.Name, err)
		}
		return ExitRuntime
	}
	// Truncate so elapsed stays a short token; sub-millisecond
	// precision is noise to an agent reader.
	elapsed := now().Sub(start).Truncate(time.Millisecond)
	if err := writer.Summary(scanned, elapsed); err != nil {
		fmt.Fprintf(stderr, "%s: writing summary: %v\n", cfg.Name, err)
		return ExitRuntime
	}
	return ExitData
}

// scopeFromValues builds the Scope from parsed common flags,
// rejecting contradictory combinations.
func scopeFromValues(v FlagValues) (Scope, error) {
	s := Scope{
		Namespace:     v.String("namespace"),
		AllNamespaces: v.Bool("A"),
		Since:         v.Duration("since"),
	}
	if s.Namespace != "" && s.AllNamespaces {
		return Scope{}, errors.New("--namespace and -A are mutually exclusive")
	}
	w, err := ParseWorkload(v.String("workload"))
	if err != nil {
		return Scope{}, err
	}
	s.Workload = w
	if s.Since < 0 {
		return Scope{}, fmt.Errorf("--since must not be negative, got %s", s.Since)
	}
	return s, nil
}

func usageError(stderr io.Writer, name string, err error) int {
	fmt.Fprintf(stderr, "%s: %v\nRun '%s --help' for usage.\n", name, err, name)
	return ExitUsage
}

// usageErr marks an error the check itself classifies as user error:
// bad positional syntax, contradictory argument+flag combinations the
// parser cannot see, or a flag that is a visible-but-unavailable
// surface (e.g. `triage spec --diff` before M3). Run routes it to the
// §4.2 usage path: stderr diagnostic, exit 2, stdout untouched.
type usageErr struct{ err error }

func (e usageErr) Error() string { return e.err.Error() }
func (e usageErr) Unwrap() error { return e.err }

// UsageErrorf returns an error that Run reports as a usage error
// (exit 2) instead of a runtime error (exit 1).
func UsageErrorf(format string, args ...any) error {
	return usageErr{fmt.Errorf(format, args...)}
}

// IsUsageError reports whether err was built by UsageErrorf (directly
// or wrapped).
func IsUsageError(err error) bool {
	var u usageErr
	return errors.As(err, &u)
}

// helpText returns cfg.Help, or a minimal flag listing when no
// generated help was supplied.
func (cfg RunConfig) helpText(fs *flag.FlagSet) string {
	if cfg.Help != "" {
		return cfg.Help
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "Usage: %s [flags]\n\nFlags:\n", cfg.Name)
	fs.SetOutput(&b)
	fs.PrintDefaults()
	fs.SetOutput(io.Discard)
	return b.String()
}
