// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package sitedoc generates the docs-site Reference section under
// docs/site/src/content/docs/reference/ — the fourth generated
// surface after --help, the MCP schemas, and the skill reference
// stubs (DESIGN.md §4.4.3: one source of truth, generated outward).
//
// Inputs, all exported data or registries so nothing here is
// hand-maintained twice:
//   - pkg/checks command metadata (one page per registered command,
//     plus the finding-kind glossary unioned from their Kinds
//     ledgers),
//   - internal/watch.FlagInventory (the sentinel page, derived from
//     the real FlagSet),
//   - pkg/inject/schema.Kinds (the signal-kind catalog, the same
//     ledger the v1 freeze test pins),
//   - internal/watch.MetricsInventory (the Prometheus metrics page,
//     names + help derived from the live collectors).
//
// The committed pages are regenerated by dev/tools/gen-site-docs; a
// drift test in this package fails CI when a metadata change is not
// followed by a re-run, exactly like internal/skilldoc.
package sitedoc

import (
	"fmt"
	"reflect"
	"regexp"
	"sort"
	"strings"

	"github.com/go-steer/k8s-lookout/internal/watch"
	"github.com/go-steer/k8s-lookout/pkg/checks"
	"github.com/go-steer/k8s-lookout/pkg/emit"
	"github.com/go-steer/k8s-lookout/pkg/inject/schema"
)

// Header is stamped on every generated page, right after the
// frontmatter, so a human editing one by hand is warned before the
// drift test tells them the hard way.
const Header = "<!-- Generated by dev/tools/gen-site-docs (internal/sitedoc). DO NOT EDIT: edit the command metadata / flag declarations / ledgers and re-run the generator. -->"

// Dir is the generated-only directory, relative to the repo root.
// Every .md file under it is owned by this package; hand-written
// reference material belongs in another section.
const Dir = "docs/site/src/content/docs/reference"

// GenerateAll renders the full Reference section. Keys are paths
// relative to the repository root.
func GenerateAll(reg *checks.Registry) map[string]string {
	out := map[string]string{
		Dir + "/index.md":         indexPage(reg),
		Dir + "/watch.md":         watchPage(),
		Dir + "/signal-kinds.md":  kindsPage(),
		Dir + "/finding-kinds.md": findingKindsPage(reg),
		Dir + "/metrics.md":       metricsPage(),
	}
	for _, c := range reg.All() {
		if c.Hidden {
			continue
		}
		out[Dir+"/"+PageFileName(c.Name)+".md"] = commandPage(c)
	}
	return out
}

// PageFileName returns the page slug for a command name:
// "triage delta" → "triage-delta".
func PageFileName(command string) string {
	return strings.ReplaceAll(command, " ", "-")
}

// ---- command pages ----------------------------------------------------

func commandPage(c checks.Command) string {
	var b strings.Builder
	frontmatter(&b, "lookout "+c.Name, c.Summary)

	fmt.Fprintf(&b, "%s\n\nMCP tool: `%s`%s\n\n", escapeProse(c.Summary), c.MCPName, c.MCPProfileNote())

	b.WriteString("## Usage\n\n")
	if c.Positional != nil {
		fmt.Fprintf(&b, "```sh\nlookout %s %s [flags]\n```\n\n", c.Name, c.Positional.Meta)
		fmt.Fprintf(&b, "`%s` — %s\n\n", c.Positional.Meta, escapeProse(c.Positional.Doc))
	} else {
		fmt.Fprintf(&b, "```sh\nlookout %s [flags]\n```\n\n", c.Name)
	}

	if len(c.Flags) > 0 {
		b.WriteString("## Flags\n\n")
		writeSpecTable(&b, c.Flags)
	}
	b.WriteString("## Common flags (every `lookout` command)\n\n")
	writeSpecTable(&b, c.CommonFlags())
	if c.GraphBacked {
		b.WriteString("## Point-in-time flags (graph-backed commands)\n\n")
		b.WriteString("This command answers from the topology graph and accepts the point-in-time flags:\n\n")
		writeSpecTable(&b, emit.GraphHistoryFlags())
	}

	if len(c.Kinds) > 0 {
		b.WriteString("## Finding kinds\n\nEvery `kind=` this command can emit, and the severities it carries them at. " +
			"Nothing else appears in its output; a kind absent from a run means the check looked and found nothing. " +
			"See the [finding-kind glossary](/reference/finding-kinds/) for the whole vocabulary.\n\n")
		b.WriteString("| Kind | Severity | Claim |\n| --- | --- | --- |\n")
		for _, k := range c.Kinds {
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", k.Name, strings.Join(k.Severity, ", "), cell(escapeProse(k.Doc)))
		}
		b.WriteString("\n")
	}

	if len(c.Output) > 0 {
		fmt.Fprintf(&b, "## Output fields\n\nBeyond the shared envelope fields (%s):\n\n",
			"`"+strings.Join(emit.EnvelopeFields(), "`, `")+"`")
		b.WriteString("| Field | Meaning |\n| --- | --- |\n")
		for _, f := range c.Output {
			fmt.Fprintf(&b, "| `%s` | %s |\n", f.Name, cell(f.Doc))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Output contract\n\n" + checks.EnvelopeContract() + "\n")

	if len(c.Examples) > 0 {
		b.WriteString("\n## Examples\n\n```sh\n")
		for _, e := range c.Examples {
			b.WriteString(e + "\n")
		}
		b.WriteString("```\n")
	}
	return b.String()
}

// writeSpecTable renders emit.FlagSpec rows with the declared type,
// defaults inline — the docs-site variant of skilldoc's flag table.
func writeSpecTable(b *strings.Builder, specs []emit.FlagSpec) {
	b.WriteString("| Flag | Type | Default | Meaning |\n| --- | --- | --- | --- |\n")
	for _, s := range specs {
		dash := "--"
		if len(s.Name) == 1 {
			dash = "-"
		}
		def := s.Default
		switch {
		case s.Type == emit.FlagBool, def == "", def == "0s", def == "0":
			def = "—"
		default:
			def = "`" + def + "`"
		}
		fmt.Fprintf(b, "| `%s%s` | %s | %s | %s |\n", dash, s.Name, s.Type, def, cell(s.Help))
	}
	b.WriteString("\n")
}

// ---- the sentinel page -------------------------------------------------

func watchPage() string {
	var b strings.Builder
	frontmatter(&b, "lookout watch",
		"The resident per-cluster sentinel: every flag, derived from the live flag surface.")
	b.WriteString(`` +
		"`lookout watch` is the watch-path half of the binary: a resident\n" +
		"per-cluster sentinel that turns leading indicators into per-incident agent\n" +
		"sessions on a core-agent daemon.\n\n" +
		"## Usage\n\n```sh\nlookout watch [flags]\n```\n\n" +
		"Signal sources are individually enabled via `--sources`; the default,\n" +
		"`auto`, probes each portable source's needs at startup and enables what the\n" +
		"deployment supports. Flags of a disabled source are\n" +
		"still validated — a nonsensical value is a config error in every mode.\n\n" +
		"## Flags\n\n" +
		"The table is generated from the sentinel's real flag declarations\n" +
		"(`internal/watch.FlagInventory`), sorted by name. The core flag\n" +
		"surface is\n" +
		"pinned by `TestFlagSurfaceFrozen`: removing or renaming one of those is a\n" +
		"breaking change to running deployments, never a refactor.\n\n")
	b.WriteString("| Flag | Type | Default | Meaning |\n| --- | --- | --- | --- |\n")
	for _, f := range watch.FlagInventory() {
		def := f.Default
		switch def {
		case "", "false", "0", "0s":
			def = "—"
		default:
			def = "`" + def + "`"
		}
		fmt.Fprintf(&b, "| `--%s` | %s | %s | %s |\n", f.Name, f.Type, def, cell(f.Help))
	}
	b.WriteString("\nSee also: [Signal kinds](/reference/signal-kinds/) — everything the sentinel can inject; [Prometheus metrics](/reference/metrics/) — the `--metrics-addr` surface.\n")
	return b.String()
}

// ---- the signal-kind catalog -------------------------------------------

func kindsPage() string {
	kinds := schema.Kinds()
	var b strings.Builder
	frontmatter(&b, "Signal kinds",
		"The signal-schema v1 kind catalog — every kind the sentinel can put on the wire, from the frozen ledger.")
	fmt.Fprintf(&b, ""+
		"The signal-schema v1 kind inventory (%d kinds), rendered from the SAME\n"+
		"exported ledger (`pkg/inject/schema`) the freeze tests in `pkg/inject` pin\n"+
		"(docs/signal-schema-v1.md). The schema is FROZEN: removing or renaming a kind\n"+
		"or a frozen field is a v2 negotiation with fleet consumers, never a\n"+
		"routine change;\n"+
		"additions are v1-additive and extend the ledger, the field pins, and the\n"+
		"schema doc in the same change.\n\n"+
		"Every payload carries a stable incident-class `fingerprint` plus\n"+
		"`cluster`/`project`/`zone` join dimensions — fleet rollup is a join, not a\n"+
		"parsing project. The one exception is the frozen reactive pair\n"+
		"(`k8s-event`, `k8s-event-followup`), whose wire shape stays\n"+
		"byte-identical for playbook back-compat and never gains the\n"+
		"identity fields.\n\n", len(kinds))

	b.WriteString("## Cross-cutting kinds\n\nEmitted by the dispatcher itself (outcome records, storms, watchboard, triage evidence) plus the frozen reactive pair.\n\n")
	b.WriteString("| Kind | Wire struct | Role |\n| --- | --- | --- |\n")
	for _, k := range kinds {
		if k.Source != "" && k.Source != "k8s-events" {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", k.Kind, structName(k.Payload), cell(k.Doc))
	}

	b.WriteString("\n## Source-namespaced kinds\n\nAll ride `inject.Payload` with the full identity stamped (`source`, `severity`, `fingerprint`, `project`, `zone`). The source column is the `--sources` name that emits the kind.\n\n")
	b.WriteString("| Kind | Source | Role |\n| --- | --- | --- |\n")
	for _, k := range kinds {
		if k.Source == "" || k.Source == "k8s-events" {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", k.Kind, k.Source, cell(k.Doc))
	}
	b.WriteString("\nField-level detail (ordered json field lists, omitempty rules, the fingerprint recipe) lives in [`docs/signal-schema-v1.md`](https://github.com/go-steer/k8s-lookout/blob/main/docs/signal-schema-v1.md).\n")
	return b.String()
}

func structName(payload any) string { return reflect.TypeOf(payload).Name() }

// ---- the finding-kind glossary ------------------------------------------

// findingKindsPage renders the read path's whole vocabulary from the
// commands' own Kinds ledgers (issue #278) — the counterpart to the
// signal-kind catalog, which does the same job for the sentinel's wire
// format. It is the page to reach for when a report contains a kind
// you do not recognise: it names the claim, the severities the kind
// can carry, and every command that can produce it.
func findingKindsPage(reg *checks.Registry) string {
	entries := reg.KindGlossary()
	var b strings.Builder
	frontmatter(&b, "Finding kinds",
		"Every kind= a read-path check can emit, its claim, and the commands that produce it — generated from the commands' own ledgers.")
	fmt.Fprintf(&b, ""+
		"Every `kind=` the read path can emit (%d in all), rendered from the same\n"+
		"`Kinds` declarations that produce each command's `--help`, MCP tool\n"+
		"schema, and reference page. A check cannot emit a kind that is not here:\n"+
		"the contract tests reject an undeclared kind, and a source sweep rejects\n"+
		"one no test happens to exercise.\n\n"+
		"The severity column is every level the kind can carry, worst first — one\n"+
		"kind often spans two, because the same defect is graver in some shapes\n"+
		"than others. A kind's absence from a run means the check looked and found\n"+
		"nothing (zero nominal state); it never means the check was skipped, which\n"+
		"is reported explicitly.\n\n"+
		"These are read-path FINDING kinds. The sentinel's wire format has its own\n"+
		"frozen vocabulary — see [Signal kinds](/reference/signal-kinds/).\n\n", len(entries))

	b.WriteString("| Kind | Severity | Claim | Emitted by |\n| --- | --- | --- | --- |\n")
	for _, e := range entries {
		cmds := make([]string, 0, len(e.Commands))
		for _, name := range e.Commands {
			cmds = append(cmds, fmt.Sprintf("[`%s`](/reference/%s/)", name, PageFileName(name)))
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
			e.Name, strings.Join(e.Severity, ", "), cell(escapeProse(e.Doc)), strings.Join(cmds, ", "))
	}
	b.WriteString("\n")
	return b.String()
}

// ---- the metrics page ----------------------------------------------------

func metricsPage() string {
	var b strings.Builder
	frontmatter(&b, "Prometheus metrics",
		"Every metric the sentinel serves on --metrics-addr, derived from the registered collectors.")
	b.WriteString("" +
		"`lookout watch --metrics-addr=host:port` serves Prometheus metrics on\n" +
		"`/metrics` (plus `/healthz`). Every metric carries the `lookout_` prefix.\n\n" +
		"Generation note (the documented choice): metric names and help strings are\n" +
		"derived from the live collectors (`internal/watch.MetricsInventory`); the\n" +
		"type and label columns are stamped per collector in that inventory because\n" +
		"the Prometheus client does not expose them before first observation. A\n" +
		"presence-check test (`TestMetricsInventoryComplete`) fails when a collector\n" +
		"is added without an inventory row.\n\n")
	b.WriteString("| Metric | Type | Labels | Meaning |\n| --- | --- | --- | --- |\n")
	for _, m := range watch.MetricsInventory() {
		labels := "—"
		if len(m.Labels) > 0 {
			labels = "`" + strings.Join(m.Labels, "`, `") + "`"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", m.Name, m.Type, labels, cell(m.Help))
	}
	b.WriteString("\n")
	return b.String()
}

// ---- the section index ----------------------------------------------------

func indexPage(reg *checks.Registry) string {
	var b strings.Builder
	frontmatter(&b, "Reference",
		"Generated reference: every read-path command, the watch sentinel's flags, the signal-kind catalog, and the Prometheus metrics.")
	b.WriteString("" +
		"Every page in this section is generated by `dev/tools/gen-site-docs` from\n" +
		"the same declarations that produce `--help`, the MCP schemas, and the skill\n" +
		"reference stubs (one source of truth, generated outward).\n" +
		"A drift test fails CI when a committed page differs from regeneration.\n\n")

	b.WriteString("## The sentinel\n\n")
	b.WriteString("- [`lookout watch`](/reference/watch/) — the resident per-cluster sentinel: full flag table.\n")
	b.WriteString("- [Signal kinds](/reference/signal-kinds/) — the frozen signal-schema v1 kind catalog.\n")
	b.WriteString("- [Prometheus metrics](/reference/metrics/) — the `--metrics-addr` surface.\n\n")

	b.WriteString("## Read-path commands\n\n")
	b.WriteString("- [Finding kinds](/reference/finding-kinds/) — the whole vocabulary these commands emit, in one table.\n\n")
	if top := reg.TopLevel(); len(top) > 0 {
		b.WriteString("Composed entry points:\n\n")
		for _, c := range top {
			writeIndexRow(&b, c)
		}
		b.WriteString("\n")
	}
	for _, g := range reg.Groups() {
		fmt.Fprintf(&b, "### `lookout %s`\n\n%s\n\n", g, escapeProse(checks.GroupSummary(g)))
		for _, c := range reg.GroupCommands(g) {
			writeIndexRow(&b, c)
		}
		b.WriteString("\n")
	}
	return b.String()
}

func writeIndexRow(b *strings.Builder, c checks.Command) {
	fmt.Fprintf(b, "- [`lookout %s`](/reference/%s/) — %s\n", c.Name, PageFileName(c.Name), escapeProse(c.Summary))
}

// ---- shared helpers --------------------------------------------------------

// frontmatter writes the Starlight frontmatter followed by the
// generated-file header. The header must come AFTER the frontmatter
// (Starlight requires the file to open with it).
func frontmatter(b *strings.Builder, title, description string) {
	fmt.Fprintf(b, "---\ntitle: %s\ndescription: %s\n---\n\n%s\n\n",
		yamlQuote(title), yamlQuote(stripSpecRefs(description)), Header)
}

// ---- design-doc citation stripping ------------------------------------

// The command metadata, flag help strings, kind docs, and metric help
// cite DESIGN.md sections ("§9.4", "(DESIGN.md §7)", "§15 Q2"). Those
// citations are useful in --help and the MCP tool descriptions, whose
// readers work inside the repository — but they are noise on the
// user-facing docs site. The site emitter strips them at render time,
// here, so the source metadata keeps its citations and the other
// generated surfaces are untouched. The passes, in order:
//
//  1. a parenthetical that is only a citation (or several) is dropped
//     whole: "(§9.4)", "(DESIGN.md §11)", "(§7.4 + §7.5)"; the
//     "(§2 marker)" shorthand for the unavailable marker drops too;
//  2. a citation opening a parenthetical loses just the citation and
//     its separator: "(§15 Q3: fixed budget…)" → "(fixed budget…)",
//     "(§8, sha256:…)" → "(sha256:…)";
//  3. a citation closing a parenthetical likewise:
//     "(per-incident mode; §7.7)" → "(per-incident mode)";
//  4. "per §X" clauses drop with the citation;
//  5. any remaining inline token drops: "the §9.2 distiller pass" →
//     "the distiller pass".
//
// A doc string that OPENED with a citation ("§7.4 outcome record: …")
// is re-capitalized after the strip.
const specRef = `(?:DESIGN\.md )?§[0-9]+(?:\.[0-9]+)*(?: Q[0-9]+)?`

var (
	refParenOnly = regexp.MustCompile(`\s*\(` + specRef + `(?:\s*[+,;/&]\s*` + specRef + `)*\)`)
	refMarker    = regexp.MustCompile(`\s*\(` + specRef + ` marker\)`)
	refParenLead = regexp.MustCompile(`\(` + specRef + `\s*[:;,]\s*`)
	refParenTail = regexp.MustCompile(`\s*[;,]\s*` + specRef + `\)`)
	refPerClause = regexp.MustCompile(`,?\s+per ` + specRef)
	refInline    = regexp.MustCompile(specRef + ` `)
	refBare      = regexp.MustCompile(`\s*` + specRef)
)

// stripSpecRefs removes DESIGN.md section citations from metadata
// prose bound for the docs site (see the policy comment above).
func stripSpecRefs(s string) string {
	openedWithRef := strings.HasPrefix(s, "§") || strings.HasPrefix(s, "DESIGN.md §")
	s = refMarker.ReplaceAllString(s, "")
	s = refParenOnly.ReplaceAllString(s, "")
	s = refParenLead.ReplaceAllString(s, "(")
	s = refParenTail.ReplaceAllString(s, ")")
	s = refPerClause.ReplaceAllString(s, "")
	s = refInline.ReplaceAllString(s, "")
	s = refBare.ReplaceAllString(s, "")
	s = strings.Join(strings.Fields(s), " ")
	if openedWithRef && len(s) > 0 && 'a' <= s[0] && s[0] <= 'z' {
		s = string(s[0]-'a'+'A') + s[1:]
	}
	return s
}

// yamlQuote renders a YAML double-quoted scalar.
func yamlQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

// cell escapes a string for use inside a markdown table cell: raw
// '<' outside code spans (would parse as HTML) and every '|' (would
// split the cell — pipes break GFM tables even inside code spans).
func cell(s string) string { return strings.ReplaceAll(escapeProse(s), "|", "\\|") }

// escapeProse prepares metadata prose for the site's markdown OUTSIDE
// `code spans` (inside them everything is already literal): raw '<'
// is backslash-escaped so placeholder tokens like <Kind> render as
// text instead of parsing as HTML, and bare product names get the
// site's code formatting (`k8s-lookout` the project, `lookout` the
// binary) — the docs-site convention; --help and the MCP schemas
// render the same metadata without backticks, so the formatting is
// applied here, never in the source strings. DESIGN.md section
// citations are stripped first, for the same reason in reverse: they
// belong on the repository-facing surfaces, not the site.
func escapeProse(s string) string {
	parts := strings.Split(stripSpecRefs(s), "`")
	for i := 0; i < len(parts); i += 2 {
		parts[i] = codeProductNames(strings.ReplaceAll(parts[i], "<", `\<`))
	}
	return strings.Join(parts, "`")
}

// productName matches a product-name token; boundary checks in
// codeProductNames keep it from firing inside paths, image refs, or
// filenames ("go-steer/k8s-lookout", "ghcr.io/go-steer/lookout",
// "lookout.db").
var productName = regexp.MustCompile(`k8s-lookout|lookout`)

// codeProductNames wraps bare "k8s-lookout" / "lookout" tokens in
// backticks. A token is bare when it is not glued to identifier, path,
// or hostname characters on either side; a trailing '.' counts as
// sentence punctuation unless it starts an extension ("lookout.db").
func codeProductNames(s string) string {
	wordy := func(c byte) bool {
		return c == '_' || c == '-' || c == '/' ||
			('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || ('0' <= c && c <= '9')
	}
	var b strings.Builder
	last := 0
	for _, m := range productName.FindAllStringIndex(s, -1) {
		start, end := m[0], m[1]
		if start > 0 && (wordy(s[start-1]) || s[start-1] == '.') {
			continue
		}
		if end < len(s) && (wordy(s[end]) ||
			(s[end] == '.' && end+1 < len(s) && wordy(s[end+1]) && s[end+1] != '-' && s[end+1] != '/')) {
			continue
		}
		b.WriteString(s[last:start])
		b.WriteByte('`')
		b.WriteString(s[start:end])
		b.WriteByte('`')
		last = end
	}
	b.WriteString(s[last:])
	return b.String()
}

// SortedPaths returns the generated paths in stable order (test and
// generator logging convenience).
func SortedPaths(files map[string]string) []string {
	out := make([]string, 0, len(files))
	for p := range files {
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}
