// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sitedoc_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/go-steer/k8s-lookout/internal/sitedoc"
	"github.com/go-steer/k8s-lookout/pkg/checks"

	_ "github.com/go-steer/k8s-lookout/pkg/checks/audit"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/bundle"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/cloudcheck"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/delta"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/events"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/findings"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/health"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/logs"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/netprobe"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/perf"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/stab"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/state"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/top"
	_ "github.com/go-steer/k8s-lookout/pkg/checks/triage"
)

// repoRoot is the working-tree root relative to this package.
const repoRoot = "../.."

// TestSitePagesAreCurrent is the §4.4.3 drift gate for the docs-site
// Reference section: the committed pages under
// docs/site/src/content/docs/reference/ must be byte-identical to
// what the current metadata generates. On failure, run
// dev/tools/gen-site-docs and commit the diff.
func TestSitePagesAreCurrent(t *testing.T) {
	files := sitedoc.GenerateAll(checks.Default())
	if len(files) == 0 {
		t.Fatal("no reference pages generated")
	}
	for _, rel := range sitedoc.SortedPaths(files) {
		got, err := os.ReadFile(filepath.Join(repoRoot, filepath.FromSlash(rel)))
		if err != nil {
			t.Errorf("%s: %v (run dev/tools/gen-site-docs)", rel, err)
			continue
		}
		if string(got) != files[rel] {
			t.Errorf("%s is stale — run dev/tools/gen-site-docs and commit the result", rel)
		}
	}

	// No stray hand-written files may hide in the generated dir.
	dir := filepath.Join(repoRoot, filepath.FromSlash(sitedoc.Dir))
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("%s: %v (run dev/tools/gen-site-docs)", dir, err)
	}
	for _, e := range entries {
		rel := sitedoc.Dir + "/" + e.Name()
		if _, ok := files[rel]; !ok {
			t.Errorf("%s: not generated by sitedoc — reference/ is generated-only, move it to another section", rel)
		}
	}
}

// TestGeneratedPagesShape spot-checks the rendered shape: every page
// opens with Starlight frontmatter and carries the DO NOT EDIT
// header immediately after it; the section's fixed pages exist.
func TestGeneratedPagesShape(t *testing.T) {
	files := sitedoc.GenerateAll(checks.Default())
	for _, fixed := range []string{"index.md", "watch.md", "signal-kinds.md", "metrics.md"} {
		if _, ok := files[sitedoc.Dir+"/"+fixed]; !ok {
			t.Errorf("fixed page %s missing from the generated set", fixed)
		}
	}
	for rel, content := range files {
		if !strings.HasPrefix(content, "---\ntitle: ") {
			t.Errorf("%s: does not open with Starlight frontmatter", rel)
		}
		if !strings.Contains(content, sitedoc.Header) {
			t.Errorf("%s: missing generated-file header", rel)
		}
	}
	// Every visible registered command has a page.
	for _, c := range checks.All() {
		if c.Hidden {
			continue
		}
		rel := sitedoc.Dir + "/" + sitedoc.PageFileName(c.Name) + ".md"
		if _, ok := files[rel]; !ok {
			t.Errorf("command %q has no generated page (%s)", c.Name, rel)
		}
	}
}
