// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package sitedoc generates the docs-site Reference section under
// docs/site/src/content/docs/reference/ — the fourth generated
// surface after --help, the MCP schemas, and the skill reference
// stubs (DESIGN.md §4.4.3: one source of truth, generated outward).
//
// Inputs, all exported data or registries so nothing here is
// hand-maintained twice:
//   - pkg/checks command metadata (one page per registered command,
//     plus the finding-kind glossary unioned from their Kinds
//     ledgers),
//   - internal/watch.FlagInventory (the sentinel page, derived from
//     the real FlagSet),
//   - pkg/inject/schema.Kinds (the signal-kind catalog, the same
//     ledger the v1 freeze test pins),
//   - internal/watch.MetricsInventory (the Prometheus metrics page,
//     names + help derived from the live collectors).
//
// The committed pages are regenerated by dev/tools/gen-site-docs; a
// drift test in this package fails CI when a metadata change is not
// followed by a re-run, exactly like internal/skilldoc.
package sitedoc

import (
	"fmt"
	"reflect"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/go-steer/k8s-lookout/internal/watch"
	"github.com/go-steer/k8s-lookout/pkg/checks"
	"github.com/go-steer/k8s-lookout/pkg/checks/scan"
	"github.com/go-steer/k8s-lookout/pkg/emit"
	"github.com/go-steer/k8s-lookout/pkg/inject/schema"
)

// Header is stamped on every generated page, right after the
// frontmatter, so a human editing one by hand is warned before the
// drift test tells them the hard way.
const Header = "<!-- Generated by dev/tools/gen-site-docs (internal/sitedoc). DO NOT EDIT: edit the command metadata / flag declarations / ledgers and re-run the generator. -->"

// Dir is the generated-only directory, relative to the repo root.
// Every .md file under it is owned by this package; hand-written
// reference material belongs in another section.
const Dir = "docs/site/src/content/docs/reference"

// DetectDir is the "What lookout detects" section: one coverage page
// per mode, so a reader landing on the site can find what each of the
// three things the binary does actually looks for, without assembling
// it from an alphabetical 147-row glossary.
//
// Unlike Dir this directory is NOT generated-only, and the generator's
// stale sweep deliberately does not run over it: `sentinel.md` is
// hand-written narrative, because the sentinel's coverage map ("what
// fails / example trigger / what it costs to enable") is not derivable
// from any declaration — it is editorial, and pinned instead by the
// tests in internal/watch. The scan and audit pages ARE derivable —
// scan's composition is declared in pkg/checks/scan and audit's is its
// registry group — so they are generated here and cannot drift.
const DetectDir = "docs/site/src/content/docs/detect"

// GenerateAll renders the Reference section plus the two generated
// coverage pages. Keys are paths relative to the repository root.
func GenerateAll(reg *checks.Registry) map[string]string {
	out := map[string]string{
		Dir + "/index.md":         indexPage(reg),
		Dir + "/watch.md":         watchPage(),
		Dir + "/signal-kinds.md":  kindsPage(),
		Dir + "/finding-kinds.md": findingKindsPage(reg),
		Dir + "/metrics.md":       metricsPage(),

		DetectDir + "/index.md": detectIndexPage(),
		DetectDir + "/scan.md":  scanCoveragePage(reg),
		DetectDir + "/audit.md": auditCoveragePage(reg),
	}
	for _, c := range reg.All() {
		if c.Hidden {
			continue
		}
		out[Dir+"/"+PageFileName(c.Name)+".md"] = commandPage(c)
	}
	return out
}

// PageFileName returns the page slug for a command name:
// "triage delta" → "triage-delta".
func PageFileName(command string) string {
	return strings.ReplaceAll(command, " ", "-")
}

// ---- command pages ----------------------------------------------------

func commandPage(c checks.Command) string {
	var b strings.Builder
	frontmatter(&b, "lookout "+c.Name, c.Summary)

	fmt.Fprintf(&b, "%s\n\nMCP tool: `%s`%s\n\n", escapeProse(c.Summary), c.MCPName, c.MCPProfileNote())

	b.WriteString("## Usage\n\n")
	if c.Positional != nil {
		fmt.Fprintf(&b, "```sh\nlookout %s %s [flags]\n```\n\n", c.Name, c.Positional.Meta)
		fmt.Fprintf(&b, "`%s` — %s\n\n", c.Positional.Meta, escapeProse(c.Positional.Doc))
	} else {
		fmt.Fprintf(&b, "```sh\nlookout %s [flags]\n```\n\n", c.Name)
	}

	if len(c.Flags) > 0 {
		b.WriteString("## Flags\n\n")
		writeSpecTable(&b, c.Flags)
	}
	b.WriteString("## Common flags (every `lookout` command)\n\n")
	writeSpecTable(&b, c.CommonFlags())
	if c.GraphBacked {
		b.WriteString("## Point-in-time flags (graph-backed commands)\n\n")
		b.WriteString("This command answers from the topology graph and accepts the point-in-time flags:\n\n")
		writeSpecTable(&b, emit.GraphHistoryFlags())
	}

	if len(c.Kinds) > 0 {
		b.WriteString("## Finding kinds\n\nEvery `kind=` this command can emit, and the severities it carries them at. " +
			"Nothing else appears in its output; a kind absent from a run means the check looked and found nothing. " +
			"See the [finding-kind glossary](/reference/finding-kinds/) for the whole vocabulary.\n\n")
		b.WriteString("| Kind | Severity | Claim |\n| --- | --- | --- |\n")
		for _, k := range c.Kinds {
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", k.Name, strings.Join(k.Severity, ", "), cell(escapeProse(k.Doc)))
		}
		b.WriteString("\n")
	}

	if len(c.Output) > 0 {
		fmt.Fprintf(&b, "## Output fields\n\nBeyond the shared envelope fields (%s):\n\n",
			"`"+strings.Join(emit.EnvelopeFields(), "`, `")+"`")
		b.WriteString("| Field | Meaning |\n| --- | --- |\n")
		for _, f := range c.Output {
			fmt.Fprintf(&b, "| `%s` | %s |\n", f.Name, cell(f.Doc))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Output contract\n\n" + checks.EnvelopeContract() + "\n")

	if len(c.Examples) > 0 {
		b.WriteString("\n## Examples\n\n```sh\n")
		for _, e := range c.Examples {
			b.WriteString(e + "\n")
		}
		b.WriteString("```\n")
	}
	return b.String()
}

// writeSpecTable renders emit.FlagSpec rows with the declared type,
// defaults inline — the docs-site variant of skilldoc's flag table.
func writeSpecTable(b *strings.Builder, specs []emit.FlagSpec) {
	b.WriteString("| Flag | Type | Default | Meaning |\n| --- | --- | --- | --- |\n")
	for _, s := range specs {
		dash := "--"
		if len(s.Name) == 1 {
			dash = "-"
		}
		def := s.Default
		switch {
		case s.Type == emit.FlagBool, def == "", def == "0s", def == "0":
			def = "—"
		default:
			def = "`" + def + "`"
		}
		fmt.Fprintf(b, "| `%s%s` | %s | %s | %s |\n", dash, s.Name, s.Type, def, cell(s.Help))
	}
	b.WriteString("\n")
}

// ---- the sentinel page -------------------------------------------------

func watchPage() string {
	var b strings.Builder
	frontmatter(&b, "lookout watch",
		"The resident per-cluster sentinel: every flag, derived from the live flag surface.")
	b.WriteString(`` +
		"`lookout watch` is the watch-path half of the binary: a resident\n" +
		"per-cluster sentinel that turns leading indicators into per-incident agent\n" +
		"sessions on a core-agent daemon.\n\n" +
		"## Usage\n\n```sh\nlookout watch [flags]\n```\n\n" +
		"Signal sources are individually enabled via `--sources`; the default,\n" +
		"`auto`, probes each portable source's needs at startup and enables what the\n" +
		"deployment supports. Flags of a disabled source are\n" +
		"still validated — a nonsensical value is a config error in every mode.\n\n" +
		"## Flags\n\n" +
		"The table is generated from the sentinel's real flag declarations\n" +
		"(`internal/watch.FlagInventory`), sorted by name. The core flag\n" +
		"surface is\n" +
		"pinned by `TestFlagSurfaceFrozen`: removing or renaming one of those is a\n" +
		"breaking change to running deployments, never a refactor.\n\n")
	b.WriteString("| Flag | Type | Default | Meaning |\n| --- | --- | --- | --- |\n")
	for _, f := range watch.FlagInventory() {
		def := f.Default
		switch def {
		case "", "false", "0", "0s":
			def = "—"
		default:
			def = "`" + def + "`"
		}
		fmt.Fprintf(&b, "| `--%s` | %s | %s | %s |\n", f.Name, f.Type, def, cell(f.Help))
	}
	b.WriteString("\nSee also: [Signal kinds](/reference/signal-kinds/) — everything the sentinel can inject; [Prometheus metrics](/reference/metrics/) — the `--metrics-addr` surface.\n")
	return b.String()
}

// ---- the signal-kind catalog -------------------------------------------

func kindsPage() string {
	kinds := schema.Kinds()
	var b strings.Builder
	frontmatter(&b, "Signal kinds",
		"The signal-schema v1 kind catalog — every kind the sentinel can put on the wire, from the frozen ledger.")
	fmt.Fprintf(&b, ""+
		"The signal-schema v1 kind inventory (%d kinds), rendered from the SAME\n"+
		"exported ledger (`pkg/inject/schema`) the freeze tests in `pkg/inject` pin\n"+
		"(docs/signal-schema-v1.md). The schema is FROZEN: removing or renaming a kind\n"+
		"or a frozen field is a v2 negotiation with fleet consumers, never a\n"+
		"routine change;\n"+
		"additions are v1-additive and extend the ledger, the field pins, and the\n"+
		"schema doc in the same change.\n\n"+
		"Every payload carries a stable incident-class `fingerprint` plus\n"+
		"`cluster`/`project`/`zone` join dimensions — fleet rollup is a join, not a\n"+
		"parsing project. The one exception is the frozen reactive pair\n"+
		"(`k8s-event`, `k8s-event-followup`), whose wire shape stays\n"+
		"byte-identical for playbook back-compat and never gains the\n"+
		"identity fields.\n\n", len(kinds))

	b.WriteString("## Cross-cutting kinds\n\nEmitted by the dispatcher itself (outcome records, storms, watchboard, triage evidence) plus the frozen reactive pair.\n\n")
	b.WriteString("| Kind | Wire struct | Role |\n| --- | --- | --- |\n")
	for _, k := range kinds {
		if k.Source != "" && k.Source != "k8s-events" {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", k.Kind, structName(k.Payload), cell(k.Doc))
	}

	b.WriteString("\n## Source-namespaced kinds\n\nAll ride `inject.Payload` with the full identity stamped (`source`, `severity`, `fingerprint`, `project`, `zone`). The source column is the `--sources` name that emits the kind.\n\n")
	b.WriteString("| Kind | Source | Role |\n| --- | --- | --- |\n")
	for _, k := range kinds {
		if k.Source == "" || k.Source == "k8s-events" {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", k.Kind, k.Source, cell(k.Doc))
	}
	b.WriteString("\nField-level detail (ordered json field lists, omitempty rules, the fingerprint recipe) lives in [`docs/signal-schema-v1.md`](https://github.com/go-steer/k8s-lookout/blob/main/docs/signal-schema-v1.md).\n")
	return b.String()
}

func structName(payload any) string { return reflect.TypeOf(payload).Name() }

// ---- the finding-kind glossary ------------------------------------------

// findingKindsPage renders the read path's whole vocabulary from the
// commands' own Kinds ledgers (issue #278) — the counterpart to the
// signal-kind catalog, which does the same job for the sentinel's wire
// format. It is the page to reach for when a report contains a kind
// you do not recognise: it names the claim, the severities the kind
// can carry, and every command that can produce it.
func findingKindsPage(reg *checks.Registry) string {
	entries := reg.KindGlossary()
	var b strings.Builder
	frontmatter(&b, "Finding kinds",
		"Every kind= a read-path check can emit, its claim, and the commands that produce it — generated from the commands' own ledgers.")
	fmt.Fprintf(&b, ""+
		"Every `kind=` the read path can emit (%d in all), rendered from the same\n"+
		"`Kinds` declarations that produce each command's `--help`, MCP tool\n"+
		"schema, and reference page. A check cannot emit a kind that is not here:\n"+
		"the contract tests reject an undeclared kind, and a source sweep rejects\n"+
		"one no test happens to exercise.\n\n"+
		"The severity column is every level the kind can carry, worst first — one\n"+
		"kind often spans two, because the same defect is graver in some shapes\n"+
		"than others. A kind's absence from a run means the check looked and found\n"+
		"nothing (zero nominal state); it never means the check was skipped, which\n"+
		"is reported explicitly.\n\n"+
		"These are read-path FINDING kinds. The sentinel's wire format has its own\n"+
		"frozen vocabulary — see [Signal kinds](/reference/signal-kinds/).\n\n", len(entries))

	b.WriteString("| Kind | Severity | Claim | Emitted by |\n| --- | --- | --- | --- |\n")
	for _, e := range entries {
		cmds := make([]string, 0, len(e.Commands))
		for _, name := range e.Commands {
			cmds = append(cmds, fmt.Sprintf("[`%s`](/reference/%s/)", name, PageFileName(name)))
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
			e.Name, strings.Join(e.Severity, ", "), cell(escapeProse(e.Doc)), strings.Join(cmds, ", "))
	}
	b.WriteString("\n")
	return b.String()
}

// ---- the metrics page ----------------------------------------------------

func metricsPage() string {
	var b strings.Builder
	frontmatter(&b, "Prometheus metrics",
		"Every metric the sentinel serves on --metrics-addr, derived from the registered collectors.")
	b.WriteString("" +
		"`lookout watch --metrics-addr=host:port` serves Prometheus metrics on\n" +
		"`/metrics` (plus `/healthz` and `/readyz`). Every metric carries the\n`lookout_` prefix.\n\n" +
		"Generation note (the documented choice): metric names and help strings are\n" +
		"derived from the live collectors (`internal/watch.MetricsInventory`); the\n" +
		"type and label columns are stamped per collector in that inventory because\n" +
		"the Prometheus client does not expose them before first observation. A\n" +
		"presence-check test (`TestMetricsInventoryComplete`) fails when a collector\n" +
		"is added without an inventory row.\n\n")
	b.WriteString("| Metric | Type | Labels | Meaning |\n| --- | --- | --- | --- |\n")
	for _, m := range watch.MetricsInventory() {
		labels := "—"
		if len(m.Labels) > 0 {
			labels = "`" + strings.Join(m.Labels, "`, `") + "`"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", m.Name, m.Type, labels, cell(m.Help))
	}
	b.WriteString("\n")
	return b.String()
}

// ---- the section index ----------------------------------------------------

func indexPage(reg *checks.Registry) string {
	var b strings.Builder
	frontmatter(&b, "Reference",
		"Generated reference: every read-path command, the watch sentinel's flags, the signal-kind catalog, and the Prometheus metrics.")
	b.WriteString("" +
		"Every page in this section is generated by `dev/tools/gen-site-docs` from\n" +
		"the same declarations that produce `--help`, the MCP schemas, and the skill\n" +
		"reference stubs (one source of truth, generated outward).\n" +
		"A drift test fails CI when a committed page differs from regeneration.\n\n")

	b.WriteString("## The sentinel\n\n")
	b.WriteString("- [`lookout watch`](/reference/watch/) — the resident per-cluster sentinel: full flag table.\n")
	b.WriteString("- [Signal kinds](/reference/signal-kinds/) — the frozen signal-schema v1 kind catalog.\n")
	b.WriteString("- [Prometheus metrics](/reference/metrics/) — the `--metrics-addr` surface.\n\n")

	b.WriteString("## Read-path commands\n\n")
	b.WriteString("- [Finding kinds](/reference/finding-kinds/) — the whole vocabulary these commands emit, in one table.\n\n")
	if top := reg.TopLevel(); len(top) > 0 {
		b.WriteString("Composed entry points:\n\n")
		for _, c := range top {
			writeIndexRow(&b, c)
		}
		b.WriteString("\n")
	}
	for _, g := range reg.Groups() {
		fmt.Fprintf(&b, "### `lookout %s`\n\n%s\n\n", g, escapeProse(checks.GroupSummary(g)))
		for _, c := range reg.GroupCommands(g) {
			writeIndexRow(&b, c)
		}
		b.WriteString("\n")
	}
	return b.String()
}

func writeIndexRow(b *strings.Builder, c checks.Command) {
	fmt.Fprintf(b, "- [`lookout %s`](/reference/%s/) — %s\n", c.Name, PageFileName(c.Name), escapeProse(c.Summary))
}

// ---- the coverage section ("What lookout detects") ----------------------

// sentinelCoveragePath is the hand-written third page of the section.
// Named here so the two generated pages can link it without a magic
// string in three places.
const sentinelCoveragePath = "/detect/sentinel/"

// detectIndexPage is the section hub: the answer to "what does this
// thing actually look for", split the way the product is — the three
// modes — rather than the way the output vocabulary is.
func detectIndexPage() string {
	var b strings.Builder
	frontmatterOrdered(&b, "Overview",
		"What each of lookout's three modes looks for: the zero-argument incident scan, the posture audit, and the resident sentinel.", 0)
	b.WriteString("" +
		"One binary does three things, and each looks for a different class of\n" +
		"problem. This section is one coverage page per mode — what it examines,\n" +
		"what it can conclude, and what it deliberately leaves to the others.\n\n")

	b.WriteString("| Mode | The question it answers | Needs |\n| --- | --- | --- |\n")
	b.WriteString("| [`lookout scan`](/detect/scan/) | *What is broken in this cluster right now?* Every target-free incident check in one call, then a dependency-edge drill-down into whatever it flagged. | a kubeconfig |\n")
	b.WriteString("| [`lookout audit`](/detect/audit/) | *What has no safety net, while it is still healthy?* Standing posture claims — no PDB, single replica, privileged containers, no NetworkPolicy, upgrades nobody is watching. | a kubeconfig |\n")
	b.WriteString("| [The sentinel](" + sentinelCoveragePath + ") | *What is about to break, and did it recover?* A resident in-cluster process turning leading indicators into agent sessions, and closing them when the symptom stays clear. | a deployment |\n")
	b.WriteString("\nThe first two need nothing deployed and take no arguments — run them\n" +
		"against a cluster you have never seen. The sentinel is the one that has to\n" +
		"live somewhere, because watching is not something a one-shot command can do.\n\n")

	b.WriteString("## Incidents, posture, and leading indicators\n\n" +
		"The split between the three is a claim about **what clears the finding**,\n" +
		"and it is why they are separate commands rather than one flag:\n\n" +
		"- An **incident** is broken now and clears itself when fixed. `scan`\n" +
		"  reports these, which is what makes its output a worklist.\n" +
		"- A **posture** finding never self-clears — a workload with one replica\n" +
		"  has one replica until someone decides otherwise. `audit` reports these,\n" +
		"  and they are `--exemptions`-auditable precisely because the answer is\n" +
		"  often \"yes, deliberately\".\n" +
		"- A **leading indicator** is neither: nothing is broken yet. Only a\n" +
		"  process that has been watching can see a slope, a flap, or a countdown,\n" +
		"  which is the sentinel's whole reason to exist.\n\n" +
		"Mixing them would flood a healthy cluster's first run and swamp the\n" +
		"`findings diff` transition stream with a flat backlog, so `audit` is off in\n" +
		"a bare scan and named in the summary's `skipped=` note so it stays\n" +
		"discoverable while off.\n\n")

	b.WriteString("## The exhaustive catalogs\n\n" +
		"These pages are organized for reading. When you have a `kind=` in hand and\n" +
		"want to know what it claims, the flat catalogs are the faster lookup:\n\n" +
		"- [Finding kinds](/reference/finding-kinds/) — every kind the read path\n" +
		"  (`scan`, `audit`, and every other command) can emit, in one table.\n" +
		"- [Signal kinds](/reference/signal-kinds/) — the sentinel's frozen\n" +
		"  signal-schema v1 wire vocabulary.\n")
	return b.String()
}

// scanCoveragePage renders what a zero-argument scan covers, grouped by
// the stage that covers it — resolved from scan's own declared
// composition (scan.Stages/scan.Groups) against the registry, so a
// stage added there appears here without anyone remembering to.
func scanCoveragePage(reg *checks.Registry) string {
	var b strings.Builder
	frontmatterOrdered(&b, "lookout scan",
		"Everything a zero-argument lookout scan looks for, grouped by the stage that looks for it — and what --include adds.", 1)
	b.WriteString("" +
		"`lookout scan` is the entry point for \"something is wrong and I do not know\n" +
		"what\": no target, no flags, nothing deployed. It runs every target-free\n" +
		"incident check in one invocation, then drills into the dependency edges of\n" +
		"whatever it flagged.\n\n" +
		"Every finding is stamped `check=<command>` — which is also the command to\n" +
		"run for the detail behind it. That is why this page is grouped by stage\n" +
		"rather than alphabetically: the heading is the follow-up call.\n\n" +
		"A kind absent from a run means the check looked and found nothing. A check\n" +
		"that could not run says so explicitly, in the stream — see\n" +
		"[what scan says about itself](#what-scan-says-about-itself) at the bottom.\n\n")

	b.WriteString("## Stage 1 — the target-free incident checks\n\n" +
		"These run on every scan, in this order: the broadest check first, so the\n" +
		"thing that is wrong is usually named before you finish reading.\n\n")
	for _, name := range scan.Stages() {
		c, ok := reg.Lookup(name)
		if !ok {
			continue
		}
		writeCoverageStage(&b, c, "###")
	}

	if c, ok := reg.Lookup("state edges"); ok {
		b.WriteString("## Stage 2 — the dependency-edge drill-down\n\n" +
			"Every workload stage 1 flagged at warning or above then has its\n" +
			"dependency edges verified: one cluster List pass and N in-memory\n" +
			"`state edges` evaluations, each rolled up to its outermost controller, so\n" +
			"twenty crashlooping pods of one Deployment are one drill-down rather than\n" +
			"twenty. `--max-drilldown` bounds it (default 20) and the summary reports\n" +
			"what it dropped.\n\n")
		writeKindTable(&b, c.Kinds)
	}

	fmt.Fprintf(&b, "## What `--include` adds\n\n"+
		"%s groups are left out of a bare scan, each for a reason that is a\n"+
		"property of the whole group. `--include=all` takes every one; `-` subtracts\n"+
		"(`all,-cloud`).\n\n", upperFirst(numberWord(len(scan.Groups()))))
	for _, g := range scan.Groups() {
		cmds := reg.GroupCommands(g)
		if len(cmds) == 0 {
			continue
		}
		fmt.Fprintf(&b, "### `--include=%s`\n\n%s\n\n", g, upperFirst(escapeProse(checks.GroupSummary(g))))
		if g == "audit" {
			fmt.Fprintf(&b, "Its %d kinds have their own page — "+
				"[what `lookout audit` checks](/detect/audit/).\n\n", countKinds(cmds))
			continue
		}
		for _, c := range cmds {
			writeCoverageStage(&b, c, "####")
		}
	}

	if c, ok := reg.Lookup("scan"); ok {
		b.WriteString("## What scan says about itself\n\n" +
			"A scan that could not run something reports that, rather than reporting a\n" +
			"smaller cluster. These kinds are the coverage claim, and they are why an\n" +
			"empty scan means \"nothing is wrong\" and not \"nothing ran\".\n\n")
		var own []checks.KindField
		for _, k := range c.Kinds {
			if strings.HasPrefix(k.Name, "scan.") {
				own = append(own, k)
			}
		}
		writeKindTable(&b, own)
	}

	b.WriteString("## See also\n\n" +
		"- [`lookout scan` reference](/reference/scan/) — flags, output fields, the\n" +
		"  full kind table in one list.\n" +
		"- [What `lookout audit` checks](/detect/audit/) — the posture half.\n" +
		"- [What the sentinel watches](" + sentinelCoveragePath + ") — the things a\n" +
		"  one-shot command structurally cannot see.\n")
	return b.String()
}

// auditCoveragePage renders the posture group's standing claims,
// grouped by subcommand — the registry group is the composition, so
// nothing here is a second list.
func auditCoveragePage(reg *checks.Registry) string {
	var b strings.Builder
	frontmatterOrdered(&b, "lookout audit",
		"Every posture claim lookout audit makes, grouped by subcommand — the absence of a safety net around something that is currently healthy.", 2)
	fmt.Fprintf(&b, ""+
		"`lookout audit` asks a different question from everything else: not \"what\n"+
		"is broken\" but **\"what has no safety net, while it is still healthy\"**. A\n"+
		"posture finding is a standing claim — it never self-clears, because a\n"+
		"workload with one replica has one replica until somebody decides\n"+
		"otherwise.\n\n"+
		"That is also why every claim here is `--exemptions`-auditable: the answer\n"+
		"is often \"yes, deliberately\", and a git-reviewed exemption file records the\n"+
		"reason and an expiry instead of the finding quietly disappearing. Covered\n"+
		"findings are **annotated** with their reason and counted as `exempt=<n>`,\n"+
		"never dropped.\n\n"+
		"Reachable two ways: the subcommands below, or `lookout scan --include=audit`\n"+
		"for the whole sweep alongside the incident checks. Like `scan`, it needs\n"+
		"nothing deployed — %s.\n\n",
		"a kubeconfig is the whole setup")

	for _, c := range reg.GroupCommands("audit") {
		if c.Hidden {
			continue
		}
		writeCoverageStage(&b, c, "##")
	}

	b.WriteString("## See also\n\n" +
		"- [Exemptions reference](/reference/audit-exemptions/) — the file format,\n" +
		"  and the check that audits the exemption file itself.\n" +
		"- [What `lookout scan` finds](/detect/scan/) — the incident half.\n" +
		"- [Finding kinds](/reference/finding-kinds/) — every read-path kind in one\n" +
		"  flat table, when you have a `kind=` and want its claim.\n")
	return b.String()
}

// writeCoverageStage renders one command as a coverage section: the
// heading is the command (and the follow-up call), the prose is its own
// one-line summary, and the table is its declared kinds. The level is
// the caller's because the two pages nest differently — scan's stages
// sit under a stage heading, audit's subcommands are the top level.
func writeCoverageStage(b *strings.Builder, c checks.Command, level string) {
	fmt.Fprintf(b, "%s [`lookout %s`](/reference/%s/)\n\n%s\n\n",
		level, c.Name, PageFileName(c.Name), escapeProse(c.Summary))
	writeKindTable(b, c.Kinds)
}

// countKinds counts the distinct kinds a set of commands declares —
// the group's claim count, derived rather than typed into prose.
func countKinds(cmds []checks.Command) int {
	seen := map[string]bool{}
	for _, c := range cmds {
		for _, k := range c.Kinds {
			seen[k.Name] = true
		}
	}
	return len(seen)
}

// numberWord spells small counts, so derived prose reads like prose.
// Above the range a bare numeral is fine — nobody writes "twenty-three"
// in a sentence about flags.
func numberWord(n int) string {
	words := []string{"zero", "one", "two", "three", "four", "five",
		"six", "seven", "eight", "nine", "ten"}
	if n >= 0 && n < len(words) {
		return words[n]
	}
	return strconv.Itoa(n)
}

// upperFirst capitalizes a summary written as a mid-sentence fragment
// (group summaries are phrased for `--help`) so it can stand alone as a
// paragraph under a heading.
func upperFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

// writeKindTable is the coverage pages' kind table: the claim column
// carries the whole point, so it is last and unabbreviated.
func writeKindTable(b *strings.Builder, kinds []checks.KindField) {
	if len(kinds) == 0 {
		return
	}
	b.WriteString("| Kind | Severity | What it means |\n| --- | --- | --- |\n")
	for _, k := range kinds {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", k.Name, strings.Join(k.Severity, ", "), cell(escapeProse(k.Doc)))
	}
	b.WriteString("\n")
}

// ---- shared helpers --------------------------------------------------------

// frontmatter writes the Starlight frontmatter followed by the
// generated-file header. The header must come AFTER the frontmatter
// (Starlight requires the file to open with it).
func frontmatter(b *strings.Builder, title, description string) {
	fmt.Fprintf(b, "---\ntitle: %s\ndescription: %s\n---\n\n%s\n\n",
		yamlQuote(title), yamlQuote(stripSpecRefs(description)), Header)
}

// frontmatterOrdered is frontmatter for a section whose sidebar order
// is curated rather than alphabetical.
func frontmatterOrdered(b *strings.Builder, title, description string, order int) {
	fmt.Fprintf(b, "---\ntitle: %s\ndescription: %s\nsidebar:\n  order: %d\n---\n\n%s\n\n",
		yamlQuote(title), yamlQuote(stripSpecRefs(description)), order, Header)
}

// ---- design-doc citation stripping ------------------------------------

// The command metadata, flag help strings, kind docs, and metric help
// cite DESIGN.md sections ("§9.4", "(DESIGN.md §7)", "§15 Q2"). Those
// citations are useful in --help and the MCP tool descriptions, whose
// readers work inside the repository — but they are noise on the
// user-facing docs site. The site emitter strips them at render time,
// here, so the source metadata keeps its citations and the other
// generated surfaces are untouched. The passes, in order:
//
//  1. a parenthetical that is only a citation (or several) is dropped
//     whole: "(§9.4)", "(DESIGN.md §11)", "(§7.4 + §7.5)"; the
//     "(§2 marker)" shorthand for the unavailable marker drops too;
//  2. a citation opening a parenthetical loses just the citation and
//     its separator: "(§15 Q3: fixed budget…)" → "(fixed budget…)",
//     "(§8, sha256:…)" → "(sha256:…)";
//  3. a citation closing a parenthetical likewise:
//     "(per-incident mode; §7.7)" → "(per-incident mode)";
//  4. "per §X" clauses drop with the citation;
//  5. any remaining inline token drops: "the §9.2 distiller pass" →
//     "the distiller pass".
//
// A doc string that OPENED with a citation ("§7.4 outcome record: …")
// is re-capitalized after the strip.
const specRef = `(?:DESIGN\.md )?§[0-9]+(?:\.[0-9]+)*(?: Q[0-9]+)?`

var (
	refParenOnly = regexp.MustCompile(`\s*\(` + specRef + `(?:\s*[+,;/&]\s*` + specRef + `)*\)`)
	refMarker    = regexp.MustCompile(`\s*\(` + specRef + ` marker\)`)
	refParenLead = regexp.MustCompile(`\(` + specRef + `\s*[:;,]\s*`)
	refParenTail = regexp.MustCompile(`\s*[;,]\s*` + specRef + `\)`)
	refPerClause = regexp.MustCompile(`,?\s+per ` + specRef)
	refInline    = regexp.MustCompile(specRef + ` `)
	refBare      = regexp.MustCompile(`\s*` + specRef)
)

// stripSpecRefs removes DESIGN.md section citations from metadata
// prose bound for the docs site (see the policy comment above).
func stripSpecRefs(s string) string {
	openedWithRef := strings.HasPrefix(s, "§") || strings.HasPrefix(s, "DESIGN.md §")
	s = refMarker.ReplaceAllString(s, "")
	s = refParenOnly.ReplaceAllString(s, "")
	s = refParenLead.ReplaceAllString(s, "(")
	s = refParenTail.ReplaceAllString(s, ")")
	s = refPerClause.ReplaceAllString(s, "")
	s = refInline.ReplaceAllString(s, "")
	s = refBare.ReplaceAllString(s, "")
	s = strings.Join(strings.Fields(s), " ")
	if openedWithRef && len(s) > 0 && 'a' <= s[0] && s[0] <= 'z' {
		s = string(s[0]-'a'+'A') + s[1:]
	}
	return s
}

// yamlQuote renders a YAML double-quoted scalar.
func yamlQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

// cell escapes a string for use inside a markdown table cell: raw
// '<' outside code spans (would parse as HTML) and every '|' (would
// split the cell — pipes break GFM tables even inside code spans).
func cell(s string) string { return strings.ReplaceAll(escapeProse(s), "|", "\\|") }

// escapeProse prepares metadata prose for the site's markdown OUTSIDE
// `code spans` (inside them everything is already literal): raw '<'
// is backslash-escaped so placeholder tokens like <Kind> render as
// text instead of parsing as HTML, and bare product names get the
// site's code formatting (`k8s-lookout` the project, `lookout` the
// binary) — the docs-site convention; --help and the MCP schemas
// render the same metadata without backticks, so the formatting is
// applied here, never in the source strings. DESIGN.md section
// citations are stripped first, for the same reason in reverse: they
// belong on the repository-facing surfaces, not the site.
func escapeProse(s string) string {
	parts := strings.Split(stripSpecRefs(s), "`")
	for i := 0; i < len(parts); i += 2 {
		parts[i] = codeProductNames(strings.ReplaceAll(parts[i], "<", `\<`))
	}
	return strings.Join(parts, "`")
}

// productName matches a product-name token; boundary checks in
// codeProductNames keep it from firing inside paths, image refs, or
// filenames ("go-steer/k8s-lookout", "ghcr.io/go-steer/lookout",
// "lookout.db").
var productName = regexp.MustCompile(`k8s-lookout|lookout`)

// codeProductNames wraps bare "k8s-lookout" / "lookout" tokens in
// backticks. A token is bare when it is not glued to identifier, path,
// or hostname characters on either side; a trailing '.' counts as
// sentence punctuation unless it starts an extension ("lookout.db").
func codeProductNames(s string) string {
	wordy := func(c byte) bool {
		return c == '_' || c == '-' || c == '/' ||
			('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || ('0' <= c && c <= '9')
	}
	var b strings.Builder
	last := 0
	for _, m := range productName.FindAllStringIndex(s, -1) {
		start, end := m[0], m[1]
		if start > 0 && (wordy(s[start-1]) || s[start-1] == '.') {
			continue
		}
		if end < len(s) && (wordy(s[end]) ||
			(s[end] == '.' && end+1 < len(s) && wordy(s[end+1]) && s[end+1] != '-' && s[end+1] != '/')) {
			continue
		}
		b.WriteString(s[last:start])
		b.WriteByte('`')
		b.WriteString(s[start:end])
		b.WriteByte('`')
		last = end
	}
	b.WriteString(s[last:])
	return b.String()
}

// SortedPaths returns the generated paths in stable order (test and
// generator logging convenience).
func SortedPaths(files map[string]string) []string {
	out := make([]string, 0, len(files))
	for p := range files {
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}
