// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package sitedoc generates the docs-site Reference section under
// docs/site/src/content/docs/reference/ — the fourth generated
// surface after --help, the MCP schemas, and the skill reference
// stubs (DESIGN.md §4.4.3: one source of truth, generated outward).
//
// Inputs, all exported data or registries so nothing here is
// hand-maintained twice:
//   - pkg/checks command metadata (one page per registered command),
//   - internal/watch.FlagInventory (the sentinel page, derived from
//     the real FlagSet),
//   - pkg/inject/schema.Kinds (the signal-kind catalog, the same
//     ledger the v1 freeze test pins),
//   - internal/watch.MetricsInventory (the Prometheus metrics page,
//     names + help derived from the live collectors).
//
// The committed pages are regenerated by dev/tools/gen-site-docs; a
// drift test in this package fails CI when a metadata change is not
// followed by a re-run, exactly like internal/skilldoc.
package sitedoc

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/go-steer/k8s-lookout/internal/watch"
	"github.com/go-steer/k8s-lookout/pkg/checks"
	"github.com/go-steer/k8s-lookout/pkg/emit"
	"github.com/go-steer/k8s-lookout/pkg/inject/schema"
)

// Header is stamped on every generated page, right after the
// frontmatter, so a human editing one by hand is warned before the
// drift test tells them the hard way.
const Header = "<!-- Generated by dev/tools/gen-site-docs (internal/sitedoc). DO NOT EDIT: edit the command metadata / flag declarations / ledgers and re-run the generator. -->"

// Dir is the generated-only directory, relative to the repo root.
// Every .md file under it is owned by this package; hand-written
// reference material belongs in another section.
const Dir = "docs/site/src/content/docs/reference"

// GenerateAll renders the full Reference section. Keys are paths
// relative to the repository root.
func GenerateAll(reg *checks.Registry) map[string]string {
	out := map[string]string{
		Dir + "/index.md":        indexPage(reg),
		Dir + "/watch.md":        watchPage(),
		Dir + "/signal-kinds.md": kindsPage(),
		Dir + "/metrics.md":      metricsPage(),
	}
	for _, c := range reg.All() {
		if c.Hidden {
			continue
		}
		out[Dir+"/"+PageFileName(c.Name)+".md"] = commandPage(c)
	}
	return out
}

// PageFileName returns the page slug for a command name:
// "triage delta" → "triage-delta".
func PageFileName(command string) string {
	return strings.ReplaceAll(command, " ", "-")
}

// ---- command pages ----------------------------------------------------

func commandPage(c checks.Command) string {
	var b strings.Builder
	frontmatter(&b, "lookout "+c.Name, c.Summary)

	fmt.Fprintf(&b, "%s\n\nMCP tool: `%s`\n\n", escapeProse(c.Summary), c.MCPName)

	b.WriteString("## Usage\n\n")
	if c.Positional != nil {
		fmt.Fprintf(&b, "```sh\nlookout %s %s [flags]\n```\n\n", c.Name, c.Positional.Meta)
		fmt.Fprintf(&b, "`%s` — %s\n\n", c.Positional.Meta, escapeProse(c.Positional.Doc))
	} else {
		fmt.Fprintf(&b, "```sh\nlookout %s [flags]\n```\n\n", c.Name)
	}

	if len(c.Flags) > 0 {
		b.WriteString("## Flags\n\n")
		writeSpecTable(&b, c.Flags)
	}
	b.WriteString("## Common flags (every lookout command)\n\n")
	writeSpecTable(&b, emit.CommonFlags())
	if c.GraphBacked {
		b.WriteString("## Point-in-time flags (graph-backed commands)\n\n")
		b.WriteString("This command answers from the topology graph and accepts the §6.6 point-in-time flags:\n\n")
		writeSpecTable(&b, emit.GraphHistoryFlags())
	}

	if len(c.Output) > 0 {
		fmt.Fprintf(&b, "## Output fields\n\nBeyond the shared envelope fields (%s):\n\n",
			"`"+strings.Join(emit.EnvelopeFields(), "`, `")+"`")
		b.WriteString("| Field | Meaning |\n| --- | --- |\n")
		for _, f := range c.Output {
			fmt.Fprintf(&b, "| `%s` | %s |\n", f.Name, cell(f.Doc))
		}
		b.WriteString("\n")
	}

	b.WriteString("## Output contract\n\n" + checks.EnvelopeContract() + "\n")

	if len(c.Examples) > 0 {
		b.WriteString("\n## Examples\n\n```sh\n")
		for _, e := range c.Examples {
			b.WriteString(e + "\n")
		}
		b.WriteString("```\n")
	}
	return b.String()
}

// writeSpecTable renders emit.FlagSpec rows with the declared type,
// defaults inline — the docs-site variant of skilldoc's flag table.
func writeSpecTable(b *strings.Builder, specs []emit.FlagSpec) {
	b.WriteString("| Flag | Type | Default | Meaning |\n| --- | --- | --- | --- |\n")
	for _, s := range specs {
		dash := "--"
		if len(s.Name) == 1 {
			dash = "-"
		}
		def := s.Default
		switch {
		case s.Type == emit.FlagBool, def == "", def == "0s", def == "0":
			def = "—"
		default:
			def = "`" + def + "`"
		}
		fmt.Fprintf(b, "| `%s%s` | %s | %s | %s |\n", dash, s.Name, s.Type, def, cell(s.Help))
	}
	b.WriteString("\n")
}

// ---- the sentinel page -------------------------------------------------

func watchPage() string {
	var b strings.Builder
	frontmatter(&b, "lookout watch",
		"The resident per-cluster sentinel: every flag, derived from the live flag surface.")
	b.WriteString(`` +
		"`lookout watch` is the watch-path half of the binary (DESIGN.md §7): a resident\n" +
		"per-cluster sentinel that turns leading indicators into per-incident agent\n" +
		"sessions on a core-agent daemon. It is the moved `k8s-event-watcher`: the M0\n" +
		"flag subset, metric names, and the `k8s-event`/`k8s-event-followup` wire shape\n" +
		"are frozen, so a predecessor deployment swaps images with zero config change.\n\n" +
		"## Usage\n\n```sh\nlookout watch [flags]\n```\n\n" +
		"Signal sources are individually enabled via `--sources` (§7.2); the default\n" +
		"is exactly the M0 surface (`k8s-events` only). Flags of a disabled source are\n" +
		"still validated — a nonsensical value is a config error in every mode.\n\n" +
		"## Flags\n\n" +
		"The table is generated from the sentinel's real flag declarations\n" +
		"(`internal/watch.FlagInventory`), sorted by name. The M0-frozen subset is\n" +
		"pinned by `TestFlagSurfaceFrozen`: removing or renaming one of those is a\n" +
		"breaking change to running deployments, never a refactor.\n\n")
	b.WriteString("| Flag | Type | Default | Meaning |\n| --- | --- | --- | --- |\n")
	for _, f := range watch.FlagInventory() {
		def := f.Default
		switch def {
		case "", "false", "0", "0s":
			def = "—"
		default:
			def = "`" + def + "`"
		}
		fmt.Fprintf(&b, "| `--%s` | %s | %s | %s |\n", f.Name, f.Type, def, cell(f.Help))
	}
	b.WriteString("\nSee also: [Signal kinds](/reference/signal-kinds/) — everything the sentinel can inject; [Prometheus metrics](/reference/metrics/) — the `--metrics-addr` surface.\n")
	return b.String()
}

// ---- the signal-kind catalog -------------------------------------------

func kindsPage() string {
	kinds := schema.Kinds()
	var b strings.Builder
	frontmatter(&b, "Signal kinds",
		"The signal-schema v1 kind catalog — every kind the sentinel can put on the wire, from the frozen ledger.")
	fmt.Fprintf(&b, ""+
		"The signal-schema v1 kind inventory (%d kinds), rendered from the SAME\n"+
		"exported ledger (`pkg/inject/schema`) the freeze tests in `pkg/inject` pin\n"+
		"(docs/signal-schema-v1.md). The schema is FROZEN: removing or renaming a kind\n"+
		"or a frozen field is a v2 negotiation with AX, never a routine change;\n"+
		"additions are v1-additive and extend the ledger, the field pins, and the\n"+
		"schema doc in the same change.\n\n"+
		"Every payload carries a stable incident-class `fingerprint` plus\n"+
		"`cluster`/`project`/`zone` join dimensions — fleet rollup is a join, not a\n"+
		"parsing project. The one exception is the frozen M0 pair, which stays\n"+
		"byte-identical to the original `k8s-event-watcher` and never gains the §8\n"+
		"identity fields.\n\n", len(kinds))

	b.WriteString("## Cross-cutting kinds\n\nEmitted by the dispatcher itself (outcome records, storms, watchboard, triage evidence) plus the frozen M0 reactive pair.\n\n")
	b.WriteString("| Kind | Wire struct | Role |\n| --- | --- | --- |\n")
	for _, k := range kinds {
		if k.Source != "" && k.Source != "k8s-events" {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", k.Kind, structName(k.Payload), cell(k.Doc))
	}

	b.WriteString("\n## Source-namespaced kinds\n\nAll ride `inject.Payload` with the full §8 identity stamped (`source`, `severity`, `fingerprint`, `project`, `zone`). The source column is the `--sources` name that emits the kind.\n\n")
	b.WriteString("| Kind | Source | Role |\n| --- | --- | --- |\n")
	for _, k := range kinds {
		if k.Source == "" || k.Source == "k8s-events" {
			continue
		}
		fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", k.Kind, k.Source, cell(k.Doc))
	}
	b.WriteString("\nField-level detail (ordered json field lists, omitempty rules, the fingerprint recipe) lives in [`docs/signal-schema-v1.md`](https://github.com/go-steer/k8s-lookout/blob/main/docs/signal-schema-v1.md).\n")
	return b.String()
}

func structName(payload any) string { return reflect.TypeOf(payload).Name() }

// ---- the metrics page ----------------------------------------------------

func metricsPage() string {
	var b strings.Builder
	frontmatter(&b, "Prometheus metrics",
		"Every metric the sentinel serves on --metrics-addr, derived from the registered collectors.")
	b.WriteString("" +
		"`lookout watch --metrics-addr=host:port` serves Prometheus metrics on\n" +
		"`/metrics` (plus `/healthz`). The `k8s_event_watcher_` prefix is frozen from\n" +
		"M0 — predecessor dashboards and alerts keep working across the image swap.\n\n" +
		"Generation note (the documented choice): metric names and help strings are\n" +
		"derived from the live collectors (`internal/watch.MetricsInventory`); the\n" +
		"type and label columns are stamped per collector in that inventory because\n" +
		"the Prometheus client does not expose them before first observation. A\n" +
		"presence-check test (`TestMetricsInventoryComplete`) fails when a collector\n" +
		"is added without an inventory row.\n\n")
	b.WriteString("| Metric | Type | Labels | Meaning |\n| --- | --- | --- | --- |\n")
	for _, m := range watch.MetricsInventory() {
		labels := "—"
		if len(m.Labels) > 0 {
			labels = "`" + strings.Join(m.Labels, "`, `") + "`"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n", m.Name, m.Type, labels, cell(m.Help))
	}
	b.WriteString("\n")
	return b.String()
}

// ---- the section index ----------------------------------------------------

func indexPage(reg *checks.Registry) string {
	var b strings.Builder
	frontmatter(&b, "Reference",
		"Generated reference: every read-path command, the watch sentinel's flags, the signal-kind catalog, and the Prometheus metrics.")
	b.WriteString("" +
		"Every page in this section is generated by `dev/tools/gen-site-docs` from\n" +
		"the same declarations that produce `--help`, the MCP schemas, and the skill\n" +
		"reference stubs (DESIGN.md §4.4.3: one source of truth, generated outward).\n" +
		"A drift test fails CI when a committed page differs from regeneration.\n\n")

	b.WriteString("## The sentinel\n\n")
	b.WriteString("- [`lookout watch`](/reference/watch/) — the resident per-cluster sentinel: full flag table.\n")
	b.WriteString("- [Signal kinds](/reference/signal-kinds/) — the frozen signal-schema v1 kind catalog.\n")
	b.WriteString("- [Prometheus metrics](/reference/metrics/) — the `--metrics-addr` surface.\n\n")

	b.WriteString("## Read-path commands\n\n")
	if top := reg.TopLevel(); len(top) > 0 {
		b.WriteString("Composed entry points:\n\n")
		for _, c := range top {
			writeIndexRow(&b, c)
		}
		b.WriteString("\n")
	}
	for _, g := range reg.Groups() {
		fmt.Fprintf(&b, "### lookout %s\n\n%s\n\n", g, escapeProse(checks.GroupSummary(g)))
		for _, c := range reg.GroupCommands(g) {
			writeIndexRow(&b, c)
		}
		b.WriteString("\n")
	}
	return b.String()
}

func writeIndexRow(b *strings.Builder, c checks.Command) {
	fmt.Fprintf(b, "- [`lookout %s`](/reference/%s/) — %s\n", c.Name, PageFileName(c.Name), escapeProse(c.Summary))
}

// ---- shared helpers --------------------------------------------------------

// frontmatter writes the Starlight frontmatter followed by the
// generated-file header. The header must come AFTER the frontmatter
// (Starlight requires the file to open with it).
func frontmatter(b *strings.Builder, title, description string) {
	fmt.Fprintf(b, "---\ntitle: %s\ndescription: %s\n---\n\n%s\n\n",
		yamlQuote(title), yamlQuote(description), Header)
}

// yamlQuote renders a YAML double-quoted scalar.
func yamlQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return `"` + s + `"`
}

// cell escapes a string for use inside a markdown table cell: raw
// '<' outside code spans (would parse as HTML) and every '|' (would
// split the cell — pipes break GFM tables even inside code spans).
func cell(s string) string { return strings.ReplaceAll(escapeProse(s), "|", "\\|") }

// escapeProse backslash-escapes raw '<' OUTSIDE `code spans` so
// placeholder tokens like <Kind> render as literal text instead of
// being parsed as HTML by the site build. Inside code spans '<' is
// already literal and must stay untouched.
func escapeProse(s string) string {
	parts := strings.Split(s, "`")
	for i := 0; i < len(parts); i += 2 {
		parts[i] = strings.ReplaceAll(parts[i], "<", `\<`)
	}
	return strings.Join(parts, "`")
}

// SortedPaths returns the generated paths in stable order (test and
// generator logging convenience).
func SortedPaths(files map[string]string) []string {
	out := make([]string, 0, len(files))
	for p := range files {
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}
